### ISSUE TITLE
Export data feature does not export actual y-axis values when Log 10 Y Axis Spacing is selected

### ISSUE THREAD

**Issue by vasangithub** [VirtualPhotonics/Vts.Gui.Wpf#43]
**Describe the bug**

When using the export data feature for a plot where the data is plotted using Log 10 Y Axis Spacing, the y values that are returned are Log 10 of the y values, not the y values themselves. The same thing happens if Log 10 X Axis Spacing is selected. Instead the actual x and y axis values should be exported independent of what axis spacing is selected to visualize the data.

**To Reproduce**
For example, Go to the Forward Solver/Analysis Panel and plot R(rho) for the default set of optical properties and s-d configuration. If you click export data, you will get a text file with the proper x and y values. However, once you select Log 10 axis spacing for either/both the x and y axes, you will no longer get the actual data values but the log 10 of those values.

**Expected behavior**
 The actual x and y axis values should be exported independent of what axis spacing is selected to visualize the data.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Comment by hayakawa16** [comment]
I can take a look at this.
